# Generated by Django 3.2 on 2025-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gateway_request_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='request url'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway_verify_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='verify url'),
        ),
    ]
