# Generated by Django 3.2 on 2025-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'Paid'), (-10, 'Not Paid')], default=-10),
        ),
    ]
