# Generated by Django 3.2 on 2025-07-28 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=64, verbose_name='COMPANY_NAME')),
                ('founded_year', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='TITLE')),
                ('year_created', models.IntegerField(default=2025)),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Black'), (2, 'White'), (3, 'Red'), (4, 'Blue'), (5, 'Green')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_list')),
                ('caption', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='car_list.company')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
