# Generated by Django 3.2 on 2025-07-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_list', '0002_alter_car_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CarBasket',
                'verbose_name_plural': 'CarBaskets',
            },
        ),
        migrations.CreateModel(
            name='CarBasketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='basket.carbasket')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='car_list.car')),
            ],
            options={
                'verbose_name': 'CarBasketLine',
                'verbose_name_plural': 'CarBasketLines',
            },
        ),
    ]
